//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18408
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Applications.Domains.Security {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SecurityResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SecurityResource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Applications.Domains.Security.SecurityResource", typeof(SecurityResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 应用程序编码不能为空 的本地化字符串。
        /// </summary>
        public static string ApplicationCodeIsEmpty {
            get {
                return ResourceManager.GetString("ApplicationCodeIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 应用程序编码 {0} 已存在，请修改 的本地化字符串。
        /// </summary>
        public static string ApplicationCodeRepeat {
            get {
                return ResourceManager.GetString("ApplicationCodeRepeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 您无权访问该应用程序 的本地化字符串。
        /// </summary>
        public static string ApplicationDeny {
            get {
                return ResourceManager.GetString("ApplicationDeny", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 应用程序名称不能为空 的本地化字符串。
        /// </summary>
        public static string ApplicationNameIsEmpty {
            get {
                return ResourceManager.GetString("ApplicationNameIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 由于您多次登陆失败，暂时被系统锁定，请稍后再试 的本地化字符串。
        /// </summary>
        public static string LockOnLoginFail {
            get {
                return ResourceManager.GetString("LockOnLoginFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 登录日志仓储不能为空 的本地化字符串。
        /// </summary>
        public static string LoginLogRepositoryIsNull {
            get {
                return ResourceManager.GetString("LoginLogRepositoryIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 拼音简码不能为空 的本地化字符串。
        /// </summary>
        public static string PinYinIsEmpty {
            get {
                return ResourceManager.GetString("PinYinIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 角色编码不能为空 的本地化字符串。
        /// </summary>
        public static string RoleCodeIsEmpty {
            get {
                return ResourceManager.GetString("RoleCodeIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 角色名称不能为空 的本地化字符串。
        /// </summary>
        public static string RoleNameIsEmpty {
            get {
                return ResourceManager.GetString("RoleNameIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 租户编码不能为空 的本地化字符串。
        /// </summary>
        public static string TenantCodeIsEmpty {
            get {
                return ResourceManager.GetString("TenantCodeIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 租户编码 {0} 已存在，请修改 的本地化字符串。
        /// </summary>
        public static string TenantCodeRepeat {
            get {
                return ResourceManager.GetString("TenantCodeRepeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 租户编号不能为空 的本地化字符串。
        /// </summary>
        public static string TenantIdIsEmpty {
            get {
                return ResourceManager.GetString("TenantIdIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 租户名称不能为空 的本地化字符串。
        /// </summary>
        public static string TenantNameIsEmpty {
            get {
                return ResourceManager.GetString("TenantNameIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 租户路径不能为空 的本地化字符串。
        /// </summary>
        public static string TenantPathIsEmpty {
            get {
                return ResourceManager.GetString("TenantPathIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 租户域名不能为空 的本地化字符串。
        /// </summary>
        public static string TenantUrlIsEmpty {
            get {
                return ResourceManager.GetString("TenantUrlIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户编号不能为空 的本地化字符串。
        /// </summary>
        public static string UserIdIsEmpty {
            get {
                return ResourceManager.GetString("UserIdIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 您的帐户已冻结，请联系管理员 的本地化字符串。
        /// </summary>
        public static string UserIsDisabled {
            get {
                return ResourceManager.GetString("UserIsDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户名或密码不能为空 的本地化字符串。
        /// </summary>
        public static string UserNameOrPasswordIsEmpty {
            get {
                return ResourceManager.GetString("UserNameOrPasswordIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户名或密码错误 的本地化字符串。
        /// </summary>
        public static string UserNameOrPasswordIsError {
            get {
                return ResourceManager.GetString("UserNameOrPasswordIsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户仓储不能为空 的本地化字符串。
        /// </summary>
        public static string UserRepositoryIsNull {
            get {
                return ResourceManager.GetString("UserRepositoryIsNull", resourceCulture);
            }
        }
    }
}
